CREATE TABLE IF NOT EXISTS PERMISSION(
    ID_PERMISSION VARCHAR(2) PRIMARY KEY,
    C NUMERIC(1,0) NOT NULL,
    R NUMERIC(1,0) NOT NULL,
    U NUMERIC(1,0) NOT NULL,
    D NUMERIC(1,0) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_TYPE(
    ID SERIAL PRIMARY KEY,
    USER_TYPE VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(32) NOT NULL,
    PERMISSION VARCHAR(2) NOT NULL,
    CONSTRAINT FK_PERMISSION FOREIGN KEY (PERMISSION) REFERENCES   PERMISSION(ID_PERMISSION)
);

CREATE TABLE IF NOT EXISTS USERS(
    USERNAME VARCHAR(32) PRIMARY KEY,
    PASSWORD VARCHAR(100) NOT NULL,
    EMAIL   VARCHAR(32)  NOT NULL,
    NAME VARCHAR(32) NOT NULL,
    LAST_NAME VARCHAR(32) NOT NULL,
    USER_TYPE SERIAL NOT NULL,
    CONSTRAINT FK_USER_TYPE FOREIGN KEY (USER_TYPE) REFERENCES USER_TYPE(ID)
);

CREATE TABLE TEAM(
  ID_TEAM VARCHAR(8),
  TEAM_NAME VARCHAR(50) NOT NULL,
  ID_INSTITUCION VARCHAR(8),
  PRIMARY KEY(ID_TEAM ),
  FOREIGN KEY (ID_INSTITUTIOON) REFERENCES INSTITUTION(ID_INSTITUTION)

);


CREATE TABLE INSTITUTION(
  ID_INSTITUTION VARCHAR(8),
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID_INSTITUCION)
  );


CREATE TABLE USERS_TEAM(
  USERNAME VARCHAR(30),
  ID_TEAM VARCHAR(8),
  PRIMARY KEY(USERNAME, ID_TEAM),
  FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME),
  FOREIGN KEY (ID_TEAM) REFERENCES TEAM(ID_TEAM)
);

CREATE TABLE CITY(
CITY_CODE CHAR(5),
CITY_NAME VARCHAR(40) NOT NULL,
PRIMARY KEY(CITY_CODE)
 );

CREATE TABLE VENUE(
ID_VENUE SERIAL,
VENUE_NAME VARCHAR(100) NOT NULL,
SHORT_NAME VARCHAR(6) NOT NULL,
V_ADDRESS VARCHAR(30) UNIQUE NOT NULL,
CITY_CODE CHAR(5),
PRIMARY KEY(ID_VENUE),
FOREIGN KEY(CITY_CODE) REFERENCES CITY(CITY_CODE)
);

CREATE TABLE STATUS(
	ID_STATUS CHAR(1) NOT NULL,
	STATUS_NAME VARCHAR(10) UNIQUE NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL,	
	PRIMARY KEY (ID_STATUS)
);

CREATE TABLE COMPETITION(
	ID_COMPETITION SERIAL NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL,
	START_INSCRIPTION TIMESTAMP NOT NULL,
	END_INSCRIPTION TIMESTAMP NOT NULL,
	START_DATE TIMESTAMP NOT NULL,
	END_DATE TIMESTAMP NOT NULL,
	TEAM_MEMBERS_MIN NUMERIC(3) NOT NULL,
	TEAM_MEMBERS_MAX NUMERIC(3) NOT NULL,
	PRIMARY KEY (ID_COMPETITION)
	);


CREATE TABLE COMPETITION_STATUS(
	ID_COMPETITION SERIAL NOT NULL,
	ID_STATUS CHAR(1) NOT NULL,
PRIMARY KEY (ID_COMPETITION),
	FOREIGN KEY (ID_STATUS) REFERENCES STATUS(ID_STATUS)
);

CREATE TABLE VENUE_COMPETITION(
ID_VENUE SERIAL,
ID_COMPETITION SERIAL,
PRIMARY KEY(ID_VENUE, ID_COMPETITION),
FOREIGN KEY(ID_VENUE) REFERENCES VENUE(ID_VENUE),
FOREIGN KEY(ID_COMPETITION) REFERENCES COMPETITION(ID_COMPETITION)
);


CREATE TABLE USER_TEAM_COMPETITION(
USERNAME VARCHAR(30),
ID_TEAM VARCHAR(8),
ID_COMPETITION INTEGER,
FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME ),
FOREIGN KEY (ID_TEAM ) REFERENCES TEAM(ID_TEAM ),
FOREIGN KEY (ID_COMPETITION ) REFERENCES COMPETITION(ID_COMPETITION ),
PRIMARY KEY (USERNAME, ID_TEAM, ID_COMPETITION )
);